In [4]:
# from pandas import Series, DataFrame

# updatedDf = df.fillna(method="fill")
# df = updatedDf
# df

# df['diff'] = df.max(axis = 1) - df.min(axis = 1)
# df

# series = ser.mode().values.tolist()
# series

In [5]:
# import pandas as pd
# import numpy as np
# from pandas import Series, DataFrame

# updatedDf = df.dropna(how = 'all', subset = ['Price', 'Category'])
# df = updatedDf
# df


# updatedHP = round(df[df.Category == 'HP']['Price'].mean(), 2)
# updatedLX = round(df[df.Category == 'LX']['Price'].mean(), 2)
# updatedMR = round(df[df.Category == 'MR']['Price'].mean(), 2)
# updatedEC = round(df[df.Category == 'EC']['Price'].mean(), 2)

# df[df.Category == 'HP'] = df[df.Category == 'HP'].fillna({'Price': updatedHP})
# df[df.Category == 'LX'] = df[df.Category == 'LX'].fillna({'Price': updatedLX})
# df[df.Category == 'MR'] = df[df.Category == 'MR'].fillna({'Price': updatedMR})
# df[df.Category == 'EC'] = df[df.Category == 'EC'].fillna({'Price': updatedEC})

# df

In [6]:
# CREATE TABLE IF NOT EXISTS Book(
# ISBM varchar(13) PRIMARY KEY,
# Title varchar(50) not null,
# AuthorName varchar(50) not null,
# FOREIGN KEY (AuthorName) REFERENCES Author(Name),
# PublicationDate date not null,
# FOREIGN KEY (PublicationDate) REFERENCES Format(Date),
# Format ENUM('hardcover', 'paperback', 'ebook', 'audiobook') not null DEFAULT 'hardcover',
# FOREIGN KEY (Format) REFERENCES Format(Type)
# Price int not null,
# FOREIGN KEY (Price) REFERENCES Format(FPrice),
# CopiesSold int null,
# FOREIGN KEY (CopiesSold) REFERENCES Format(CSold)
# );

# CREATE TABLE IF NOT EXISTS Author(
# Id int PRIMARY KEY,
# Name vachar(50) not null,
# Email varchar(50) not null,
# );

# CREATE TABLE IF NOT EXISTS ISBN(
# PublishingCompany varchar(50) PRIMARY KEY,
# Id varchar(13) not null,
# FOREIGN KEY (Id) REFERENCES Book(ISBM)
# );

# CREATE TABLE IF NOT EXISTS Format(
# Type ENUM('hardcover', 'paperback', 'ebook', 'audiobook') not null DEFAULT 'hardcover' PRIMARY KEY,
# FPrice int not null,
# Date date not null,
# CSold int null
# );

In [7]:
# SELECT AVG(Price) 
# FROM Room, Hotel
# WHERE City = "London"

# SELECT COUNT(GuestNo)
# FROM Guest, Booking
# WHERE Guest.GuestNo == Booking.GuestNo AND City == "New York"  AND MONTH(DateTo) == "08"

# SELECT RoomNo, HotelNo
# FROM Room, Hotel, Booking
# WHERE Room.HotelNo == Hotel.HotelNo AND HotelChainName == "Hilton" AND NOT EXISTS (GuestNo)

# SELECT HotelChainName AS HotelChain, Country AS Country, COUNT(Price) AS Revenue,
# FROM Hotel, Room, Booking
# WHERE YEAR(DateTo) == "2021"
# GROUP BY Country
# GROUP BY HotelChainName

In [9]:
# import pandas as pd
# import numpy as np
# from pandas import Series, DataFrame

# updatedDf = df

# for x in updatedDf.index:
#     if(not isinstance(updatedDf.loc[x, "Category"], str)):
#         if (updatedDf[updatedDf.Category == "HP"]["Price"].max() >= updatedDf.loc[x, "Price"] >= updatedDf[updatedDf.Category == "HP"]["Price"].min()):
#             updatedDf.loc[x, "Category"] = "HP"
            
#         elif(updatedDf[updatedDf.Category == "LX"]["Price"].max() >= updatedDf.loc[x, "Price"] >= updatedDf[updatedDf.Category == "LX"]["Price"].min()):
#             updatedDf.loc[x, "Category"] = "LX"
            
#         elif(updatedDf[updatedDf.Category == "MR"]["Price"].max() >= updatedDf.loc[x, "Price"] >= updatedDf[updatedDf.Category == "MR"]["Price"].min()):
#             updatedDf.loc[x, "Category"] = "MR"

#         elif(updatedDf[updatedDf.Category == "EC"]["Price"].max() >= updatedDf.loc[x, "Price"] >= updatedDf[updatedDf.Category == "EC"]["Price"].min()):
#             updatedDf.loc[x, "Category"] = "EC"
            
#         else:
#             continue

# df = updatedDf
# df

In [10]:
# CREATE TABLE IF NOT EXISTS Book(
#     ISBM varchar(13) PRIMARY KEY,
#     Title varchar(50) not null,
#     AuthorName varchar(50) not null,
#     FOREIGN KEY (AuthorName) REFERENCES Author(Name),
#     PublicationDate date not null,
#     FOREIGN KEY (PublicationDate) REFERENCES Format(Date),
#     Format ENUM('hardcover', 'paperback', 'ebook', 'audiobook') not null DEFAULT 'hardcover',
#     FOREIGN KEY (Format) REFERENCES Format(Type),
#     Price int not null,
#     FOREIGN KEY (Price) REFERENCES Format(FPrice),
#     CopiesSold int null,
#     FOREIGN KEY (CopiesSold) REFERENCES Format(CSold)
# );

# CREATE TABLE IF NOT EXISTS Author(
#     Id int PRIMARY KEY,
#     Name vachar(50) not null,
#     Email varchar(50) not null
# );

# CREATE TABLE IF NOT EXISTS ISBN(
#     PublishingCompany varchar(50) PRIMARY KEY,
#     Id varchar(13) not null,
#     FOREIGN KEY (Id) REFERENCES Book(ISBM)
# );

# CREATE TABLE IF NOT EXISTS Format(
#     Type ENUM('hardcover', 'paperback', 'ebook', 'audiobook') not null DEFAULT 'hardcover' PRIMARY KEY,
#     FPrice int not null,
#     Date date not null,
#     CSold int null
# );

In [11]:
# import pandas as pd
# import numpy as np
# from pandas import Series, DataFrame

# def twoPointTwo(dataframe):
    
#     updatedDf = dataframe

#     updatedHP = round(updatedDf[updatedDf.Category == "HP"]["Price"].mean(), 2)
#     updatedLX = round(updatedDf[updatedDf.Category == "LX"]["Price"].mean(), 2)
#     updatedMR = round(updatedDf[updatedDf.Category == "MR"]["Price"].mean(), 2)
#     updatedEC = round(updatedDf[updatedDf.Category == "EC"]["Price"].mean(), 2)

#     updatedDf[updatedDf.Category == "HP"] = updatedDf[updatedDf.Category == "HP"].fillna({"Price": updatedHP})
#     updatedDf[updatedDf.Category == "LX"] = updatedDf[updatedDf.Category == "LX"].fillna({"Price": updatedLX})
#     updatedDf[updatedDf.Category == "MR"] = updatedDf[updatedDf.Category == "MR"].fillna({"Price": updatedMR})
#     updatedDf[updatedDf.Category == "EC"] = updatedDf[updatedDf.Category == "EC"].fillna({"Price": updatedEC})

#     dataframe = updatedDf
#     return dataframe

# twoPointTwo(df)

In [12]:
# import pandas as pd
# import numpy as np
# from pandas import Series, DataFrame

# def twoPointThree(dataframe):
    
#     updatedDf = dataframe

#     for x in updatedDf.index:
#         if(not isinstance(updatedDf.loc[x, "Category"], str)):
#             if (updatedDf[updatedDf.Category == "HP"]["Price"].max() >= updatedDf.loc[x, "Price"] >= updatedDf[updatedDf.Category == "HP"]["Price"].min()):
#                 updatedDf.loc[x, "Category"] = "HP"

#             elif(updatedDf[updatedDf.Category == "LX"]["Price"].max() >= updatedDf.loc[x, "Price"] >= updatedDf[updatedDf.Category == "LX"]["Price"].min()):
#                 updatedDf.loc[x, "Category"] = "LX"

#             elif(updatedDf[updatedDf.Category == "MR"]["Price"].max() >= updatedDf.loc[x, "Price"] >= updatedDf[updatedDf.Category == "MR"]["Price"].min()):
#                 updatedDf.loc[x, "Category"] = "MR"

#             elif(updatedDf[updatedDf.Category == "EC"]["Price"].max() >= updatedDf.loc[x, "Price"] >= updatedDf[updatedDf.Category == "EC"]["Price"].min()):
#                 updatedDf.loc[x, "Category"] = "EC"

#             else:
#                 continue

#     dataframe = updatedDf
#     return dataframe

# twoPointThree(df)

In [13]:
# import pandas as pd
# import numpy as np
# from pandas import Series, DataFrame

# def twoPointOne(dataframe):
#     updatedDf = dataframe.dropna(how = 'all', subset = ['Price', 'Category'])
#     dataframe = updatedDf
#     return dataframe

# twoPointOne(df)

In [14]:
# from pandas import Series, DataFrame

# def onePointThree(series):
#     series.mode().values.tolist()
#     return series

# onePointThree(ser)